# Generated by Django 4.2.2 on 2023-06-22 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testgen', '0004_purchase_delete_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='last_name',
        ),
    ]
