# Generated by Django 4.2.2 on 2023-06-22 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo',
            new_name='TodoClass',
        ),
    ]
