# Generated by Django 4.2.2 on 2023-06-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokenapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authenticate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='MyTable',
        ),
    ]
