# Generated by Django 4.2.2 on 2023-06-23 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CType', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CollageCode', models.IntegerField()),
                ('CollageName', models.CharField(max_length=50)),
                ('CollageDistrict', models.CharField(max_length=50)),
                ('collage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collage', to='nestserial.collage')),
            ],
        ),
    ]
